spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8080
          predicates:
            - Path=/products/**
          filters:
            - PrefixPath=/api/v1

        - id: order-service
          uri: http://localhost:8081
          predicates:
            - Path=/orders/**
          filters:
            - PrefixPath=/api/v1

        - id: inventory-service
          uri: http://localhost:8082
          predicates:
            - Path=/inventory/**
          filters:
            - PrefixPath=/api/v1

        # swagger docs routes
        - id: product-service-swagger
          uri: http://localhost:8080
          predicates:
            - Path=/aggregate/product-service/v3/api-docs
          filters:
            - RewritePath=/aggregate/product-service/v3/api-docs, /v3/api-docs

        - id: order-service-swagger
          uri: http://localhost:8081
          predicates:
            - Path=/aggregate/order-service/v3/api-docs
          filters:
            - RewritePath=/aggregate/order-service/v3/api-docs, /v3/api-docs

        - id: inventory-service-swagger
          uri: http://localhost:8082
          predicates:
            - Path=/aggregate/inventory-service/v3/api-docs
          filters:
            - RewritePath=/aggregate/inventory-service/v3/api-docs, /v3/api-docs

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9092/realms/demo
server:
  port: 9000

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: product-service-swagger
        url: /aggregate/product-service/v3/api-docs
      - name: order-service-swagger
        url: /aggregate/order-service/v3/api-docs
      - name: inventory-service-swagger
        url: /aggregate/inventory-service/v3/api-docs
  api-docs:
    path: /v3/api-docs
