services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=product-service'
      - 'MONGO_INITDB_ROOT_PASSWORD=mongo'
      - 'MONGO_INITDB_ROOT_USERNAME=mongo'
    ports:
      - '27017:27017'
