spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: ${GIT_URI}
          default-label: master

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888
